In [1]:
import pandas as pd
import numpy as np
import numpy_financial as npf
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.formula.api import ols
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")
from numpy import *

from ggplot import *
from scipy.stats import logistic
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import *
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, export_graphviz
import graphviz
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.svm import SVC, SVR
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler


from linearmodels.iv import IV2SLS
from scipy import stats
from scipy.stats import trim_mean #trimmed mean
from scipy.stats import * #chi2_contingency로 카이제곱통계량계산
from scipy.stats import norm

import keyword
import random

#open api 불러올 때 필요한 것
from urllib.request import urlopen #request package 설치
from bs4 import BeautifulSoup #bs4 package 설치

# 그래프에서 한글 깨지지 않기 위헤 사용함
from matplotlib import rcParams
from matplotlib import font_manager,rc

rcParams['axes.unicode_minus']=False
plt.rcParams['font.family']='Malgun Gothic'
font_name=font_manager.FontProperties(fname='c:/Windows/Fonts/malgun.ttf').get_name()
rc('font',family=font_name)

import FinanceDataReader as fdr
import plotly.graph_objects as go
import plotly.subplots as ms
import math

import tensorflow as tf

import qgrid

In [2]:
df=pd.read_csv('c:/temp/final5_20240619.csv')
df.head()

Age  Survived
0  29.00         1
1   2.00         0
2  30.00         0
3  25.00         0
4   0.92         1

In [7]:
# y가 범주형일 때 ML -> 경사하강법으로 예측하기, using sigmoid


# 데이터 전처리 1
x_data=df['Age']
y_data=df['Survived']

# 데이터 전처리 2 : ML 방식은 tensor flow 에서 사용해야 한다. 
# data frame -> numpy array 형식으로 바꿔야 한다.
x_data=x_data.to_numpy()
y_data=y_data.to_numpy()

# 데이터 전처리 4: 'float32'로 바꿔야 tf에서 사용 가능
x_data=x_data.astype('float32')
y_data=y_data.astype('float32')



In [9]:
# 경사하강법 적용
learning_rate=tf.Variable(0.001)
W=tf.Variable(0.1,name='Weignt')
b=tf.Variable(0.1,name='bias')
# 초기값 보기: print(W.numpy(),b.numpy()) 
for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis=tf.sigmoid(W*x_data+b) # tensor flow 내에 내장된 sigmoid 함수 들어가 있다. hypothesis=H(x)
        cost=-tf.reduce_mean(y_data*tf.math.log(hypothesis)+(1-y_data)*tf.math.log(1-hypothesis))
        W_grad, b_grad=tape.gradient(cost,[W,b])
        # W, b를 경사하강법에 의해 update 한다
        W.assign_sub(learning_rate*W_grad)
        b.assign_sub(learning_rate*b_grad)
        # 다른 부분은 다 같고, hypothesis, cost만 잘 정의하면 됨
    
    # 결과보기
    if i%100==0:
        print(i,cost.numpy(),W.numpy().flatten(),b.numpy())

0 1.9721208 [0.08307168] 0.09949335
100 0.6770929 [-0.01364062] 0.09601
200 0.67708683 [-0.01361944] 0.09523657
300 0.6770809 [-0.01359834] 0.094466485
400 0.677075 [-0.01357735] 0.09369976
500 0.6770692 [-0.01355644] 0.09293636
600 0.6770634 [-0.01353563] 0.092176296
700 0.6770577 [-0.0135149] 0.09141951
800 0.6770521 [-0.01349427] 0.090666056
900 0.6770464 [-0.01347373] 0.08991585
1000 0.6770408 [-0.01345327] 0.08916892


In [10]:
alpha=0.08916892
beta=-0.01345327
z=alpha+beta*40
pr_1=1/(1+np.exp(-z))
print(pr_1)

0.3896076167125493


In [11]:
a=tf.constant([[1,2,3],[4,5,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [12]:
b=tf.constant([[1,2],[3,4],[5,6]])
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [13]:
c=tf.matmul(a,b)
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]])>

In [14]:
c.ndim

2

In [15]:
c.shape

TensorShape([2, 2])