In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

from ggplot import *
from scipy.stats import logistic
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import *
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, export_graphviz
import graphviz
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.svm import SVC, SVR
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [3]:
file1="c:/temp/iris.csv"
iris=pd.read_csv(file1)
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
# Gaussain NB 전체

X=iris[['Sepal.Length','Sepal.Width','Petal.Length','Petal.Width']]
y=iris['Species']

gnb=GaussianNB().fit(X,y)
pred=gnb.predict(X)
confusion_matrix(y,pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]], dtype=int64)

In [7]:
# CCR 1
(50+47+47)/(50+47+47+3+3)

0.96

In [6]:
# Gaussain NB train test split
X=iris[['Sepal.Length','Sepal.Width','Petal.Length','Petal.Width']]
y=iris['Species']
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,train_size=0.7)

gnb=GaussianNB()
result2=gnb.fit(X_train,y_train)
pred2=gnb.predict(X_test)
confusion_matrix(y_test,pred2)

array([[16,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 11]], dtype=int64)

In [8]:
# Multinomial NB 전체
file2="c:/temp/multi_nb.csv"
data2=pd.read_csv(file2)

X=data2[['x1','x2']]
y=data2['y']
clf=MultinomialNB()
result3=clf.fit(X,y)
pred3=result3.predict(X)
confusion_matrix(y,pred3)

array([[ 72, 131],
       [ 10, 287]], dtype=int64)

In [9]:
# CCR 3
(72+287)/(72+287+131+10)

0.718

In [11]:
# Multinomial NB train test split

X=data2[['x1','x2']]
y=data2['y']
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=0)

clf=MultinomialNB()
result4=clf.fit(X_train,y_train)
pred4=result4.predict(X_test)
confusion_matrix(y_test,pred4)

array([[22, 41],
       [ 2, 85]], dtype=int64)

In [12]:
# CCR 4
(22+85)/(22+85+41+2)

0.7133333333333334

In [14]:
# Bernoulli NB 전체

np.random.seed(1234)
X=np.random.randint(2,size=(500,10))
y=np.random.randint(2,size=(500,1))
X_train=X[:450,:]
X_test=X[450:,:]
y_train=y[:450,:]
y_test=y[450:,:]

clf=BernoulliNB()
result5=clf.fit(X_train,y_train)
pred5=result5.predict(X_test)
confusion_matrix(y_test,pred5)

array([[ 4, 21],
       [ 3, 22]], dtype=int64)

In [15]:
# CCR 5
(4+22)/(4+22+21+3)

0.52

In [16]:
# Laplace Smoothing

np.random.seed(1234)
X=np.random.randint(2,size=(500,10))
y=np.random.randint(2,size=(500,1))
X_train=X[:450,:]
X_test=X[450:,:]
y_train=y[:450,:]
y_test=y[450:,:]

clf=BernoulliNB(alpha=1)
result6=clf.fit(X_train,y_train)
pred6=result6.predict(X_test)
confusion_matrix(y_test,pred6)

array([[ 4, 21],
       [ 3, 22]], dtype=int64)

In [17]:
# CCR 6 , CCR 5와 같음. 확률이 0인게 없으니까
(4+22)/(4+22+21+3)

0.52