In [1]:
pip install ggplot

In [7]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [8]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
import pandas as pd

In [10]:
from ggplot import*

In [11]:
file1="c:/temp/Auto.csv"
Auto=pd.read_csv(file1)
Auto

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
392       1            ford mustang gl  
393       2                  vw pickup  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[397 rows x 9 columns]

In [12]:
Auto.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [13]:
Auto.tail()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin             name  
392       1  ford mustang gl  
393       2        vw pickup  
394       1    dodge rampage  
395       1      ford ranger  
396       1       chevy s-10

In [14]:
Auto.shape

(397, 9)

In [15]:
Auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
year              int64
origin            int64
name             object
dtype: object

In [16]:
file2="c:/temp/Auto1.xlsx"
Auto1=pd.read_excel(file2)
Auto1

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
392       1            ford mustang gl  
393       2                  vw pickup  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[397 rows x 9 columns]

In [17]:
Auto.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [18]:
Auto.tail()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin             name  
392       1  ford mustang gl  
393       2        vw pickup  
394       1    dodge rampage  
395       1      ford ranger  
396       1       chevy s-10

In [19]:
Auto.shape

(397, 9)

In [20]:
Auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
year              int64
origin            int64
name             object
dtype: object

In [21]:
Auto.describe

<bound method NDFrame.describe of       mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  


In [22]:
Auto.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  397.000000  397.000000    397.000000   397.000000    397.000000   
mean    23.515869    5.458438    193.532746  2970.261965     15.555668   
std      7.825804    1.701577    104.379583   847.904119      2.749995   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.000000  2223.000000     13.800000   
50%     23.000000    4.000000    146.000000  2800.000000     15.500000   
75%     29.000000    8.000000    262.000000  3609.000000     17.100000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

             year      origin  
count  397.000000  397.000000  
mean    75.994962    1.574307  
std      3.690005    0.802549  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [23]:
Auto['acceleration'].describe()

count    397.000000
mean      15.555668
std        2.749995
min        8.000000
25%       13.800000
50%       15.500000
75%       17.100000
max       24.800000
Name: acceleration, dtype: float64

In [24]:
Auto[['acceleration','mpg']].describe()

acceleration         mpg
count    397.000000  397.000000
mean      15.555668   23.515869
std        2.749995    7.825804
min        8.000000    9.000000
25%       13.800000   17.500000
50%       15.500000   23.000000
75%       17.100000   29.000000
max       24.800000   46.600000

In [25]:
Auto[['mpg','cylinders','year']].describe()

mpg   cylinders        year
count  397.000000  397.000000  397.000000
mean    23.515869    5.458438   75.994962
std      7.825804    1.701577    3.690005
min      9.000000    3.000000   70.000000
25%     17.500000    4.000000   73.000000
50%     23.000000    4.000000   76.000000
75%     29.000000    8.000000   79.000000
max     46.600000    8.000000   82.000000

In [26]:
Auto=pd.read_csv(file1)
Auto

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
392       1            ford mustang gl  
393       2                  vw pickup  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[397 rows x 9 columns]

In [27]:
Auto['origin'].value_counts()

1    248
3     79
2     70
Name: origin, dtype: int64

In [28]:
Auto['origin']=Auto['origin'].astype('category')
Auto.dtypes

mpg              float64
cylinders          int64
displacement     float64
horsepower        object
weight             int64
acceleration     float64
year               int64
origin          category
name              object
dtype: object

In [29]:
Auto.describe(include='all')

mpg   cylinders  displacement horsepower       weight  \
count   397.000000  397.000000    397.000000        397   397.000000   
unique         NaN         NaN           NaN         94          NaN   
top            NaN         NaN           NaN        150          NaN   
freq           NaN         NaN           NaN         22          NaN   
mean     23.515869    5.458438    193.532746        NaN  2970.261965   
std       7.825804    1.701577    104.379583        NaN   847.904119   
min       9.000000    3.000000     68.000000        NaN  1613.000000   
25%      17.500000    4.000000    104.000000        NaN  2223.000000   
50%      23.000000    4.000000    146.000000        NaN  2800.000000   
75%      29.000000    8.000000    262.000000        NaN  3609.000000   
max      46.600000    8.000000    455.000000        NaN  5140.000000   

        acceleration        year  origin        name  
count     397.000000  397.000000   397.0         397  
unique           NaN         NaN     3.0         304  
top              NaN         NaN     1.0  ford pinto  
freq             NaN         NaN   248.0           6  
mean       15.555668   75.994962     NaN         NaN  
std         2.749995    3.690005     NaN         NaN  
min         8.000000   70.000000     NaN         NaN  
25%        13.800000   73.000000     NaN         NaN  
50%        15.500000   76.000000     NaN         NaN  
75%        17.100000   79.000000     NaN         NaN  
max        24.800000   82.000000     NaN         NaN

In [30]:
import numpy as np

In [31]:
Auto.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  397.000000  397.000000    397.000000   397.000000    397.000000   
mean    23.515869    5.458438    193.532746  2970.261965     15.555668   
std      7.825804    1.701577    104.379583   847.904119      2.749995   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.000000  2223.000000     13.800000   
50%     23.000000    4.000000    146.000000  2800.000000     15.500000   
75%     29.000000    8.000000    262.000000  3609.000000     17.100000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

             year  
count  397.000000  
mean    75.994962  
std      3.690005  
min     70.000000  
25%     73.000000  
50%     76.000000  
75%     79.000000  
max     82.000000

In [32]:
np.mean(Auto['displacement'])

193.53274559193954

In [34]:
np.std(Auto['cylinders'])

1.699432585509141

In [35]:
np.min(Auto['weight'])

1613

In [36]:
np.count(Auto['mpg'])

AttributeError: module 'numpy' has no attribute 'count'

In [37]:
np.max(Auto['mpg'])

46.6

In [39]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [41]:
x1=np.array([[1,2,3],[4,5,6]])
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
x2=np.array([[1,2,3],[4,5,6],[7,8,9]])
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [50]:
matplotlib.inline
import matplotlib.inline as plt

NameError: name 'matplotlib' is not defined