In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

from ggplot import *
from scipy.stats import logistic
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [11]:
file1="c:/temp/wisc_bc_data.csv"
bc_data=pd.read_csv(file1)
bc_data

id diagnosis  radius_mean  texture_mean  perimeter_mean  \
0     87139402         B        12.32         12.39           78.85   
1      8910251         B        10.60         18.95           69.28   
2       905520         B        11.04         16.83           70.92   
3       868871         B        11.28         13.39           73.00   
4      9012568         B        15.19         13.21           97.65   
..         ...       ...          ...           ...             ...   
564  911320502         B        13.17         18.22           84.28   
565     898677         B        10.26         14.71           66.20   
566     873885         M        15.28         22.41           98.92   
567     911201         B        14.53         13.98           93.86   
568    9012795         M        21.37         15.10          141.30   

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
0        464.1          0.10280           0.06981         0.03987   
1        346.4          0.09688           0.11470         0.06387   
2        373.2          0.10770           0.07804         0.03046   
3        384.8          0.11640           0.11360         0.04635   
4        711.8          0.07963           0.06934         0.03393   
..         ...              ...               ...             ...   
564      537.3          0.07466           0.05994         0.04859   
565      321.6          0.09882           0.09159         0.03581   
566      710.6          0.09057           0.10520         0.05375   
567      644.2          0.10990           0.09242         0.06895   
568     1386.0          0.10010           0.15150         0.19320   

     points_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0        0.03700  ...         13.50          15.64            86.97   
1        0.02642  ...         11.88          22.94            78.28   
2        0.02480  ...         12.41          26.44            79.93   
3        0.04796  ...         11.92          15.77            76.53   
4        0.02657  ...         16.20          15.73           104.50   
..           ...  ...           ...            ...              ...   
564      0.02870  ...         14.90          23.89            95.10   
565      0.02037  ...         10.88          19.48            70.89   
566      0.03263  ...         17.80          28.03           113.80   
567      0.06495  ...         15.80          16.93           103.10   
568      0.12550  ...         22.69          21.84           152.10   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0         549.1            0.1385             0.1266          0.12420   
1         424.8            0.1213             0.2515          0.19160   
2         471.4            0.1369             0.1482          0.10670   
3         434.0            0.1367             0.1822          0.08669   
4         819.1            0.1126             0.1737          0.13620   
..          ...               ...                ...              ...   
564       687.6            0.1282             0.1965          0.18760   
565       357.1            0.1360             0.1636          0.07162   
566       973.1            0.1301             0.3299          0.36300   
567       749.9            0.1347             0.1478          0.13730   
568      1535.0            0.1192             0.2840          0.40240   

     points_worst  symmetry_worst  dimension_worst  
0         0.09391          0.2827          0.06771  
1         0.07926          0.2940          0.07587  
2         0.07431          0.2998          0.07881  
3         0.08611          0.2102          0.06784  
4         0.08178          0.2487          0.06766  
..            ...             ...              ...  
564       0.10450          0.2235          0.06925  
565       0.04074          0.2434          0.08488  
566       0.12260          0.3175          0.09772  
567       0.10690          0.2606          0.07810  
568       0.19660

In [12]:
pd.value_counts(bc_data['diagnosis'])

B    357
M    212
Name: diagnosis, dtype: int64

In [13]:
bc_data.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  points_mean  \
count       569.000000        569.000000      569.000000   569.000000   
mean          0.096360          0.104341        0.088799     0.048919   
std           0.014064          0.052813        0.079720     0.038803   
min           0.052630          0.019380        0.000000     0.000000   
25%           0.086370          0.064920        0.029560     0.020310   
50%           0.095870          0.092630        0.061540     0.033500   
75%           0.105300          0.130400        0.130700     0.074000   
max           0.163400          0.345400        0.426800     0.201200   

       symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count     569.000000  ...    569.000000     569.000000       569.000000   
mean        0.181162  ...     16.269190      25.677223       107.261213   
std         0.027414  ...      4.833242       6.146258        33.602542   
min         0.106000  ...      7.930000      12.020000        50.410000   
25%         0.161900  ...     13.010000      21.080000        84.110000   
50%         0.179200  ...     14.970000      25.410000        97.660000   
75%         0.195700  ...     18.790000      29.720000       125.400000   
max         0.304000  ...     36.040000      49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       points_worst  symmetry_worst  dimension_worst  
count    569.000000      569.000000       569.000000  
mean       0.114606        0.290076         0.083946  
std        0.065732        0.061867         0.018061  
min        0.000000        0.156500         0.055040  
25%        0.064930        0.250400         0.071460  
50%        0.099930        0.282200         0.080040  
75%        0.161400        0.317900         0.092080  
max        0.291000        0.663800         0.207500  

[8 rows x 31 columns]

In [14]:
bc_data['radius_mean'].describe()

count    569.000000
mean      14.127292
std        3.524049
min        6.981000
25%       11.700000
50%       13.370000
75%       15.780000
max       28.110000
Name: radius_mean, dtype: float64

In [15]:
bc_data[['radius_mean','area_mean','smoothness_mean']].describe()

radius_mean    area_mean  smoothness_mean
count   569.000000   569.000000       569.000000
mean     14.127292   654.889104         0.096360
std       3.524049   351.914129         0.014064
min       6.981000   143.500000         0.052630
25%      11.700000   420.300000         0.086370
50%      13.370000   551.100000         0.095870
75%      15.780000   782.700000         0.105300
max      28.110000  2501.000000         0.163400

In [16]:
# 위에 describe 본 벼눗는 다 연속형 변수
# diagnosis 와 id를 제외한 위의 30개 변수는 다 x 변수. 거리를 측정하기 위해 사용하는 것들.
# 우선 x 변수를 지정해야한다. 
# x 변수가 몇개 안되면 위에 describe 에 썼던 것 처럼 [[]] 해서 쓰면되는데, 지금은 30개를 다 쓰기 힘듦.

# 난 2번째 부터 32번째 까지 다  x 변수 하고 싶다. 어디서부터 어디까지 라고 나타낼 수 없나?
# 첫번째 : 전체부터 다 가져와라 
# 왜 32번째? : 
# [:,2:32] : (0,1,)2번부터 앞에서 1부터 셌을 때 32번째 위치까지 가져와라 



X1=bc_data.iloc[:,2:32]
X1

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          12.32         12.39           78.85      464.1          0.10280   
1          10.60         18.95           69.28      346.4          0.09688   
2          11.04         16.83           70.92      373.2          0.10770   
3          11.28         13.39           73.00      384.8          0.11640   
4          15.19         13.21           97.65      711.8          0.07963   
..           ...           ...             ...        ...              ...   
564        13.17         18.22           84.28      537.3          0.07466   
565        10.26         14.71           66.20      321.6          0.09882   
566        15.28         22.41           98.92      710.6          0.09057   
567        14.53         13.98           93.86      644.2          0.10990   
568        21.37         15.10          141.30     1386.0          0.10010   

     compactness_mean  concavity_mean  points_mean  symmetry_mean  \
0             0.06981         0.03987      0.03700         0.1959   
1             0.11470         0.06387      0.02642         0.1922   
2             0.07804         0.03046      0.02480         0.1714   
3             0.11360         0.04635      0.04796         0.1771   
4             0.06934         0.03393      0.02657         0.1721   
..                ...             ...          ...            ...   
564           0.05994         0.04859      0.02870         0.1454   
565           0.09159         0.03581      0.02037         0.1633   
566           0.10520         0.05375      0.03263         0.1727   
567           0.09242         0.06895      0.06495         0.1650   
568           0.15150         0.19320      0.12550         0.1973   

     dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.05955  ...         13.50          15.64            86.97   
1           0.06491  ...         11.88          22.94            78.28   
2           0.06340  ...         12.41          26.44            79.93   
3           0.06072  ...         11.92          15.77            76.53   
4           0.05544  ...         16.20          15.73           104.50   
..              ...  ...           ...            ...              ...   
564         0.05549  ...         14.90          23.89            95.10   
565         0.07005  ...         10.88          19.48            70.89   
566         0.06317  ...         17.80          28.03           113.80   
567         0.06121  ...         15.80          16.93           103.10   
568         0.06183  ...         22.69          21.84           152.10   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0         549.1            0.1385             0.1266          0.12420   
1         424.8            0.1213             0.2515          0.19160   
2         471.4            0.1369             0.1482          0.10670   
3         434.0            0.1367             0.1822          0.08669   
4         819.1            0.1126             0.1737          0.13620   
..          ...               ...                ...              ...   
564       687.6            0.1282             0.1965          0.18760   
565       357.1            0.1360             0.1636          0.07162   
566       973.1            0.1301             0.3299          0.36300   
567       749.9            0.1347             0.1478          0.13730   
568      1535.0            0.1192             0.2840          0.40240   

     points_worst  symmetry_worst  dimension_worst  
0         0.09391          0.2827          0.06771  
1         0.07926          0.2940          0.07587  
2         0.07431          0.2998          0.07881  
3         0.08611          0.2102          0.06784  
4         0.08178          0.2487          0.06766  
..            ...             ...              ...  
564       0.10450          0.2235          0.06925  
565       0.04074          0.2434          0.0848

In [17]:
# min max normalize

scaler=preprocessing.MinMaxScaler()
#minmaxnormalize 된 변수 X11
X11=scaler.fit_transform(X1)
X11
# 다 0과 1사이로 표준화됨.

array([[0.25268588, 0.0906324 , 0.24227766, ..., 0.32271478, 0.24876799,
        0.08310376],
       [0.17128118, 0.31247886, 0.17614539, ..., 0.27237113, 0.27104278,
        0.136626  ],
       [0.19210564, 0.24078458, 0.18747841, ..., 0.25536082, 0.28247585,
        0.15590975],
       ...,
       [0.3927777 , 0.42948935, 0.38096883, ..., 0.42130584, 0.31736645,
        0.27994228],
       [0.35728146, 0.14440311, 0.34600235, ..., 0.36735395, 0.20520402,
        0.15125279],
       [0.68100715, 0.18227934, 0.67383042, ..., 0.67560137, 0.22964715,
        0.20739866]])

In [18]:
# 정규화
X12=preprocessing.scale(X1)
X12

array([[-0.51329651, -1.60559452, -0.54037561, ..., -0.31513306,
        -0.11932056, -0.89972108],
       [-1.00180093, -0.07903849, -0.93456583, ..., -0.53820271,
         0.06348865, -0.44752801],
       [-0.87683468, -0.57237672, -0.8670139 , ..., -0.61357437,
         0.15731992, -0.28460551],
       ...,
       [ 0.32738551,  0.72612674,  0.28631171, ...,  0.12171802,
         0.44366709,  0.7633076 ],
       [ 0.11437486, -1.23559085,  0.07788929, ..., -0.11733956,
        -0.47685008, -0.32395074],
       [ 2.05703196, -0.97495933,  2.03195239, ...,  1.24848623,
        -0.27624528,  0.15040866]])

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
y=bc_data['diagnosis']
X_train, X_test, y_train, y_test=train_test_split(X11,y,train_size=0.7,random_state=0)
X_train

array([[0.37763264, 0.31755157, 0.36790823, ..., 0.51168385, 0.27537946,
        0.19467401],
       [0.30380046, 0.36557322, 0.30993021, ..., 0.704811  , 0.39818648,
        0.36639118],
       [0.11619102, 0.29117349, 0.11077327, ..., 0.17360825, 0.17524147,
        0.17263545],
       ...,
       [0.1113162 , 0.41359486, 0.10517587, ..., 0.08810997, 0.17149616,
        0.12390135],
       [0.3757395 , 0.17653027, 0.36390021, ..., 0.39415808, 0.22136803,
        0.18162141],
       [0.37006011, 0.26885357, 0.3599613 , ..., 0.28549828, 0.40114331,
        0.11681753]])

In [22]:
# Train set 이용해서 KNN 실행

# 우선 K를 정하자. 안정하면 그냥 default를 1로 함.
# K를 3으로 하자 : 가까운 3명 통해 판단

clf=KNeighborsClassifier(n_neighbors=3)
result=clf.fit(X_train,y_train)
result

KNeighborsClassifier(n_neighbors=3)

In [23]:
y_pred=clf.predict(X_test)
y_pred

array(['M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'M', 'B', 'B',
       'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B',
       'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'M', 'B', 'B',
       'B', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B',
       'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'B',
       'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B',
       'M', 'B'], dtype=object)

In [24]:
len(y_pred)
# test의 171개에 대한 예측값을 제시한 것.

171

In [25]:
# y_test와 y_pred 간에 얼마나 매칭 되는지 알아보자 by confusion matrix의 ccr

# 이 패키지를 사용해서 구한 것: from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred)

array([[111,   2],
       [  3,  55]], dtype=int64)

In [26]:
# 올바르게 분류한 정도가 97%이다
(111+55)/171

0.9707602339181286

In [27]:
# k를 3으로 할 필요는 없지. 다른 k로도 해보고 ccr 비교해보면됨.

# X11 min-amx, X12 표준 정규화 둘 중에 다 시도해보고 ccr 더 큰게 좋은 것.
# 중간에 코드 바꿔서 해보고 ccr 비교해보면 됨.










# 자 자 시험문제 (ccr, sensitivity, specificity)
# Sensitivity (진양성비율 / Pr(y_hat=1|y=1) -> 55/58
# 아직 0, 1 정의 안함
# 0=B 음성, 1=M 양성

# Specificity 특이도 -> 111/113

In [28]:
X1=bc_data.iloc[:,2:32]
X12=preprocessing.scale(X1)
y=bc_data['diagnosis']

In [29]:
X_train, X_test, y_train, y_test=train_test_split(X12,y,train_size=0.7,random_state=0)

In [30]:
clf=KNeighborsClassifier(n_neighbors=3)
result=clf.fit(X_train,y_train)
result

KNeighborsClassifier(n_neighbors=3)

In [31]:
y_pred_12=clf.predict(X_test)
y_pred

array(['M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'B', 'B', 'M', 'B', 'B',
       'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'B',
       'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'M',
       'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'M', 'B', 'B',
       'B', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B',
       'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'B',
       'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B',
       'M', 'B'], dtype=object)

In [32]:
len(y_pred)

171

In [33]:
confusion_matrix(y_test,y_pred_12)

array([[112,   1],
       [  3,  55]], dtype=int64)

In [34]:
# ccr
(112+55)/171

0.9766081871345029

In [ ]:
# ccr 더 커짐 X12가 더 좋네